services:
  - type: web
    name: e-gram-web
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

  - type: worker
    name: e-gram-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
